package com.ycs.ezlink.mybatis.dto;

public class AlertTemplateMaster {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALERT_TEMPLATE_MASTER.ALERT_TEMPLATE_ID
     *
     * @mbggenerated
     */
    private String alertTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALERT_TEMPLATE_MASTER.ALERT_TYPE
     *
     * @mbggenerated
     */
    private String alertType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALERT_TEMPLATE_MASTER.ALERT_CONTENT
     *
     * @mbggenerated
     */
    private String alertContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALERT_TEMPLATE_MASTER.SMS_PASSWORD
     *
     * @mbggenerated
     */
    private String smsPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALERT_TEMPLATE_MASTER.SMS_USERID
     *
     * @mbggenerated
     */
    private String smsUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALERT_TEMPLATE_MASTER.TECH_STUDIO_CAMPAIGN_ID
     *
     * @mbggenerated
     */
    private String techStudioCampaignId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALERT_TEMPLATE_MASTER.EMAIL_SUBJECT
     *
     * @mbggenerated
     */
    private String emailSubject;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALERT_TEMPLATE_MASTER.ALERT_TEMPLATE_ID
     *
     * @return the value of ALERT_TEMPLATE_MASTER.ALERT_TEMPLATE_ID
     *
     * @mbggenerated
     */
    public String getAlertTemplateId() {
        return alertTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALERT_TEMPLATE_MASTER.ALERT_TEMPLATE_ID
     *
     * @param alertTemplateId the value for ALERT_TEMPLATE_MASTER.ALERT_TEMPLATE_ID
     *
     * @mbggenerated
     */
    public void setAlertTemplateId(String alertTemplateId) {
        this.alertTemplateId = alertTemplateId == null ? null : alertTemplateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALERT_TEMPLATE_MASTER.ALERT_TYPE
     *
     * @return the value of ALERT_TEMPLATE_MASTER.ALERT_TYPE
     *
     * @mbggenerated
     */
    public String getAlertType() {
        return alertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALERT_TEMPLATE_MASTER.ALERT_TYPE
     *
     * @param alertType the value for ALERT_TEMPLATE_MASTER.ALERT_TYPE
     *
     * @mbggenerated
     */
    public void setAlertType(String alertType) {
        this.alertType = alertType == null ? null : alertType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALERT_TEMPLATE_MASTER.ALERT_CONTENT
     *
     * @return the value of ALERT_TEMPLATE_MASTER.ALERT_CONTENT
     *
     * @mbggenerated
     */
    public String getAlertContent() {
        return alertContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALERT_TEMPLATE_MASTER.ALERT_CONTENT
     *
     * @param alertContent the value for ALERT_TEMPLATE_MASTER.ALERT_CONTENT
     *
     * @mbggenerated
     */
    public void setAlertContent(String alertContent) {
        this.alertContent = alertContent == null ? null : alertContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALERT_TEMPLATE_MASTER.SMS_PASSWORD
     *
     * @return the value of ALERT_TEMPLATE_MASTER.SMS_PASSWORD
     *
     * @mbggenerated
     */
    public String getSmsPassword() {
        return smsPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALERT_TEMPLATE_MASTER.SMS_PASSWORD
     *
     * @param smsPassword the value for ALERT_TEMPLATE_MASTER.SMS_PASSWORD
     *
     * @mbggenerated
     */
    public void setSmsPassword(String smsPassword) {
        this.smsPassword = smsPassword == null ? null : smsPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALERT_TEMPLATE_MASTER.SMS_USERID
     *
     * @return the value of ALERT_TEMPLATE_MASTER.SMS_USERID
     *
     * @mbggenerated
     */
    public String getSmsUserid() {
        return smsUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALERT_TEMPLATE_MASTER.SMS_USERID
     *
     * @param smsUserid the value for ALERT_TEMPLATE_MASTER.SMS_USERID
     *
     * @mbggenerated
     */
    public void setSmsUserid(String smsUserid) {
        this.smsUserid = smsUserid == null ? null : smsUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALERT_TEMPLATE_MASTER.TECH_STUDIO_CAMPAIGN_ID
     *
     * @return the value of ALERT_TEMPLATE_MASTER.TECH_STUDIO_CAMPAIGN_ID
     *
     * @mbggenerated
     */
    public String getTechStudioCampaignId() {
        return techStudioCampaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALERT_TEMPLATE_MASTER.TECH_STUDIO_CAMPAIGN_ID
     *
     * @param techStudioCampaignId the value for ALERT_TEMPLATE_MASTER.TECH_STUDIO_CAMPAIGN_ID
     *
     * @mbggenerated
     */
    public void setTechStudioCampaignId(String techStudioCampaignId) {
        this.techStudioCampaignId = techStudioCampaignId == null ? null : techStudioCampaignId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALERT_TEMPLATE_MASTER.EMAIL_SUBJECT
     *
     * @return the value of ALERT_TEMPLATE_MASTER.EMAIL_SUBJECT
     *
     * @mbggenerated
     */
    public String getEmailSubject() {
        return emailSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALERT_TEMPLATE_MASTER.EMAIL_SUBJECT
     *
     * @param emailSubject the value for ALERT_TEMPLATE_MASTER.EMAIL_SUBJECT
     *
     * @mbggenerated
     */
    public void setEmailSubject(String emailSubject) {
        this.emailSubject = emailSubject == null ? null : emailSubject.trim();
    }
}