package com.ycs.ezlink.mybatis.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AlertQueueExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ALERT_QUEUE
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ALERT_QUEUE
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ALERT_QUEUE
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALERT_QUEUE
     *
     * @mbggenerated
     */
    public AlertQueueExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALERT_QUEUE
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALERT_QUEUE
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALERT_QUEUE
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALERT_QUEUE
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALERT_QUEUE
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALERT_QUEUE
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALERT_QUEUE
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALERT_QUEUE
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALERT_QUEUE
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALERT_QUEUE
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ALERT_QUEUE
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAlertQIdIsNull() {
            addCriterion("ALERT_Q_ID is null");
            return (Criteria) this;
        }

        public Criteria andAlertQIdIsNotNull() {
            addCriterion("ALERT_Q_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAlertQIdEqualTo(Integer value) {
            addCriterion("ALERT_Q_ID =", value, "alertQId");
            return (Criteria) this;
        }

        public Criteria andAlertQIdNotEqualTo(Integer value) {
            addCriterion("ALERT_Q_ID <>", value, "alertQId");
            return (Criteria) this;
        }

        public Criteria andAlertQIdGreaterThan(Integer value) {
            addCriterion("ALERT_Q_ID >", value, "alertQId");
            return (Criteria) this;
        }

        public Criteria andAlertQIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ALERT_Q_ID >=", value, "alertQId");
            return (Criteria) this;
        }

        public Criteria andAlertQIdLessThan(Integer value) {
            addCriterion("ALERT_Q_ID <", value, "alertQId");
            return (Criteria) this;
        }

        public Criteria andAlertQIdLessThanOrEqualTo(Integer value) {
            addCriterion("ALERT_Q_ID <=", value, "alertQId");
            return (Criteria) this;
        }

        public Criteria andAlertQIdIn(List<Integer> values) {
            addCriterion("ALERT_Q_ID in", values, "alertQId");
            return (Criteria) this;
        }

        public Criteria andAlertQIdNotIn(List<Integer> values) {
            addCriterion("ALERT_Q_ID not in", values, "alertQId");
            return (Criteria) this;
        }

        public Criteria andAlertQIdBetween(Integer value1, Integer value2) {
            addCriterion("ALERT_Q_ID between", value1, value2, "alertQId");
            return (Criteria) this;
        }

        public Criteria andAlertQIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ALERT_Q_ID not between", value1, value2, "alertQId");
            return (Criteria) this;
        }

        public Criteria andAlertTypeIsNull() {
            addCriterion("ALERT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andAlertTypeIsNotNull() {
            addCriterion("ALERT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andAlertTypeEqualTo(String value) {
            addCriterion("ALERT_TYPE =", value, "alertType");
            return (Criteria) this;
        }

        public Criteria andAlertTypeNotEqualTo(String value) {
            addCriterion("ALERT_TYPE <>", value, "alertType");
            return (Criteria) this;
        }

        public Criteria andAlertTypeGreaterThan(String value) {
            addCriterion("ALERT_TYPE >", value, "alertType");
            return (Criteria) this;
        }

        public Criteria andAlertTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ALERT_TYPE >=", value, "alertType");
            return (Criteria) this;
        }

        public Criteria andAlertTypeLessThan(String value) {
            addCriterion("ALERT_TYPE <", value, "alertType");
            return (Criteria) this;
        }

        public Criteria andAlertTypeLessThanOrEqualTo(String value) {
            addCriterion("ALERT_TYPE <=", value, "alertType");
            return (Criteria) this;
        }

        public Criteria andAlertTypeLike(String value) {
            addCriterion("ALERT_TYPE like", value, "alertType");
            return (Criteria) this;
        }

        public Criteria andAlertTypeNotLike(String value) {
            addCriterion("ALERT_TYPE not like", value, "alertType");
            return (Criteria) this;
        }

        public Criteria andAlertTypeIn(List<String> values) {
            addCriterion("ALERT_TYPE in", values, "alertType");
            return (Criteria) this;
        }

        public Criteria andAlertTypeNotIn(List<String> values) {
            addCriterion("ALERT_TYPE not in", values, "alertType");
            return (Criteria) this;
        }

        public Criteria andAlertTypeBetween(String value1, String value2) {
            addCriterion("ALERT_TYPE between", value1, value2, "alertType");
            return (Criteria) this;
        }

        public Criteria andAlertTypeNotBetween(String value1, String value2) {
            addCriterion("ALERT_TYPE not between", value1, value2, "alertType");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andSmsTextIsNull() {
            addCriterion("SMS_TEXT is null");
            return (Criteria) this;
        }

        public Criteria andSmsTextIsNotNull() {
            addCriterion("SMS_TEXT is not null");
            return (Criteria) this;
        }

        public Criteria andSmsTextEqualTo(String value) {
            addCriterion("SMS_TEXT =", value, "smsText");
            return (Criteria) this;
        }

        public Criteria andSmsTextNotEqualTo(String value) {
            addCriterion("SMS_TEXT <>", value, "smsText");
            return (Criteria) this;
        }

        public Criteria andSmsTextGreaterThan(String value) {
            addCriterion("SMS_TEXT >", value, "smsText");
            return (Criteria) this;
        }

        public Criteria andSmsTextGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_TEXT >=", value, "smsText");
            return (Criteria) this;
        }

        public Criteria andSmsTextLessThan(String value) {
            addCriterion("SMS_TEXT <", value, "smsText");
            return (Criteria) this;
        }

        public Criteria andSmsTextLessThanOrEqualTo(String value) {
            addCriterion("SMS_TEXT <=", value, "smsText");
            return (Criteria) this;
        }

        public Criteria andSmsTextLike(String value) {
            addCriterion("SMS_TEXT like", value, "smsText");
            return (Criteria) this;
        }

        public Criteria andSmsTextNotLike(String value) {
            addCriterion("SMS_TEXT not like", value, "smsText");
            return (Criteria) this;
        }

        public Criteria andSmsTextIn(List<String> values) {
            addCriterion("SMS_TEXT in", values, "smsText");
            return (Criteria) this;
        }

        public Criteria andSmsTextNotIn(List<String> values) {
            addCriterion("SMS_TEXT not in", values, "smsText");
            return (Criteria) this;
        }

        public Criteria andSmsTextBetween(String value1, String value2) {
            addCriterion("SMS_TEXT between", value1, value2, "smsText");
            return (Criteria) this;
        }

        public Criteria andSmsTextNotBetween(String value1, String value2) {
            addCriterion("SMS_TEXT not between", value1, value2, "smsText");
            return (Criteria) this;
        }

        public Criteria andEmailTextIsNull() {
            addCriterion("EMAIL_TEXT is null");
            return (Criteria) this;
        }

        public Criteria andEmailTextIsNotNull() {
            addCriterion("EMAIL_TEXT is not null");
            return (Criteria) this;
        }

        public Criteria andEmailTextEqualTo(String value) {
            addCriterion("EMAIL_TEXT =", value, "emailText");
            return (Criteria) this;
        }

        public Criteria andEmailTextNotEqualTo(String value) {
            addCriterion("EMAIL_TEXT <>", value, "emailText");
            return (Criteria) this;
        }

        public Criteria andEmailTextGreaterThan(String value) {
            addCriterion("EMAIL_TEXT >", value, "emailText");
            return (Criteria) this;
        }

        public Criteria andEmailTextGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL_TEXT >=", value, "emailText");
            return (Criteria) this;
        }

        public Criteria andEmailTextLessThan(String value) {
            addCriterion("EMAIL_TEXT <", value, "emailText");
            return (Criteria) this;
        }

        public Criteria andEmailTextLessThanOrEqualTo(String value) {
            addCriterion("EMAIL_TEXT <=", value, "emailText");
            return (Criteria) this;
        }

        public Criteria andEmailTextLike(String value) {
            addCriterion("EMAIL_TEXT like", value, "emailText");
            return (Criteria) this;
        }

        public Criteria andEmailTextNotLike(String value) {
            addCriterion("EMAIL_TEXT not like", value, "emailText");
            return (Criteria) this;
        }

        public Criteria andEmailTextIn(List<String> values) {
            addCriterion("EMAIL_TEXT in", values, "emailText");
            return (Criteria) this;
        }

        public Criteria andEmailTextNotIn(List<String> values) {
            addCriterion("EMAIL_TEXT not in", values, "emailText");
            return (Criteria) this;
        }

        public Criteria andEmailTextBetween(String value1, String value2) {
            addCriterion("EMAIL_TEXT between", value1, value2, "emailText");
            return (Criteria) this;
        }

        public Criteria andEmailTextNotBetween(String value1, String value2) {
            addCriterion("EMAIL_TEXT not between", value1, value2, "emailText");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andScheduledTimeIsNull() {
            addCriterion("SCHEDULED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andScheduledTimeIsNotNull() {
            addCriterion("SCHEDULED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andScheduledTimeEqualTo(Date value) {
            addCriterion("SCHEDULED_TIME =", value, "scheduledTime");
            return (Criteria) this;
        }

        public Criteria andScheduledTimeNotEqualTo(Date value) {
            addCriterion("SCHEDULED_TIME <>", value, "scheduledTime");
            return (Criteria) this;
        }

        public Criteria andScheduledTimeGreaterThan(Date value) {
            addCriterion("SCHEDULED_TIME >", value, "scheduledTime");
            return (Criteria) this;
        }

        public Criteria andScheduledTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SCHEDULED_TIME >=", value, "scheduledTime");
            return (Criteria) this;
        }

        public Criteria andScheduledTimeLessThan(Date value) {
            addCriterion("SCHEDULED_TIME <", value, "scheduledTime");
            return (Criteria) this;
        }

        public Criteria andScheduledTimeLessThanOrEqualTo(Date value) {
            addCriterion("SCHEDULED_TIME <=", value, "scheduledTime");
            return (Criteria) this;
        }

        public Criteria andScheduledTimeIn(List<Date> values) {
            addCriterion("SCHEDULED_TIME in", values, "scheduledTime");
            return (Criteria) this;
        }

        public Criteria andScheduledTimeNotIn(List<Date> values) {
            addCriterion("SCHEDULED_TIME not in", values, "scheduledTime");
            return (Criteria) this;
        }

        public Criteria andScheduledTimeBetween(Date value1, Date value2) {
            addCriterion("SCHEDULED_TIME between", value1, value2, "scheduledTime");
            return (Criteria) this;
        }

        public Criteria andScheduledTimeNotBetween(Date value1, Date value2) {
            addCriterion("SCHEDULED_TIME not between", value1, value2, "scheduledTime");
            return (Criteria) this;
        }

        public Criteria andDeliveredStatusIsNull() {
            addCriterion("DELIVERED_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andDeliveredStatusIsNotNull() {
            addCriterion("DELIVERED_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveredStatusEqualTo(String value) {
            addCriterion("DELIVERED_STATUS =", value, "deliveredStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveredStatusNotEqualTo(String value) {
            addCriterion("DELIVERED_STATUS <>", value, "deliveredStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveredStatusGreaterThan(String value) {
            addCriterion("DELIVERED_STATUS >", value, "deliveredStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveredStatusGreaterThanOrEqualTo(String value) {
            addCriterion("DELIVERED_STATUS >=", value, "deliveredStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveredStatusLessThan(String value) {
            addCriterion("DELIVERED_STATUS <", value, "deliveredStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveredStatusLessThanOrEqualTo(String value) {
            addCriterion("DELIVERED_STATUS <=", value, "deliveredStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveredStatusLike(String value) {
            addCriterion("DELIVERED_STATUS like", value, "deliveredStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveredStatusNotLike(String value) {
            addCriterion("DELIVERED_STATUS not like", value, "deliveredStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveredStatusIn(List<String> values) {
            addCriterion("DELIVERED_STATUS in", values, "deliveredStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveredStatusNotIn(List<String> values) {
            addCriterion("DELIVERED_STATUS not in", values, "deliveredStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveredStatusBetween(String value1, String value2) {
            addCriterion("DELIVERED_STATUS between", value1, value2, "deliveredStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveredStatusNotBetween(String value1, String value2) {
            addCriterion("DELIVERED_STATUS not between", value1, value2, "deliveredStatus");
            return (Criteria) this;
        }

        public Criteria andRetryCountIsNull() {
            addCriterion("RETRY_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andRetryCountIsNotNull() {
            addCriterion("RETRY_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andRetryCountEqualTo(Short value) {
            addCriterion("RETRY_COUNT =", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountNotEqualTo(Short value) {
            addCriterion("RETRY_COUNT <>", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountGreaterThan(Short value) {
            addCriterion("RETRY_COUNT >", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountGreaterThanOrEqualTo(Short value) {
            addCriterion("RETRY_COUNT >=", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountLessThan(Short value) {
            addCriterion("RETRY_COUNT <", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountLessThanOrEqualTo(Short value) {
            addCriterion("RETRY_COUNT <=", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountIn(List<Short> values) {
            addCriterion("RETRY_COUNT in", values, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountNotIn(List<Short> values) {
            addCriterion("RETRY_COUNT not in", values, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountBetween(Short value1, Short value2) {
            addCriterion("RETRY_COUNT between", value1, value2, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountNotBetween(Short value1, Short value2) {
            addCriterion("RETRY_COUNT not between", value1, value2, "retryCount");
            return (Criteria) this;
        }

        public Criteria andMobileNoIsNull() {
            addCriterion("MOBILE_NO is null");
            return (Criteria) this;
        }

        public Criteria andMobileNoIsNotNull() {
            addCriterion("MOBILE_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMobileNoEqualTo(String value) {
            addCriterion("MOBILE_NO =", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotEqualTo(String value) {
            addCriterion("MOBILE_NO <>", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoGreaterThan(String value) {
            addCriterion("MOBILE_NO >", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoGreaterThanOrEqualTo(String value) {
            addCriterion("MOBILE_NO >=", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoLessThan(String value) {
            addCriterion("MOBILE_NO <", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoLessThanOrEqualTo(String value) {
            addCriterion("MOBILE_NO <=", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoLike(String value) {
            addCriterion("MOBILE_NO like", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotLike(String value) {
            addCriterion("MOBILE_NO not like", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoIn(List<String> values) {
            addCriterion("MOBILE_NO in", values, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotIn(List<String> values) {
            addCriterion("MOBILE_NO not in", values, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoBetween(String value1, String value2) {
            addCriterion("MOBILE_NO between", value1, value2, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotBetween(String value1, String value2) {
            addCriterion("MOBILE_NO not between", value1, value2, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andEmailToIsNull() {
            addCriterion("EMAIL_TO is null");
            return (Criteria) this;
        }

        public Criteria andEmailToIsNotNull() {
            addCriterion("EMAIL_TO is not null");
            return (Criteria) this;
        }

        public Criteria andEmailToEqualTo(String value) {
            addCriterion("EMAIL_TO =", value, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToNotEqualTo(String value) {
            addCriterion("EMAIL_TO <>", value, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToGreaterThan(String value) {
            addCriterion("EMAIL_TO >", value, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL_TO >=", value, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToLessThan(String value) {
            addCriterion("EMAIL_TO <", value, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToLessThanOrEqualTo(String value) {
            addCriterion("EMAIL_TO <=", value, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToLike(String value) {
            addCriterion("EMAIL_TO like", value, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToNotLike(String value) {
            addCriterion("EMAIL_TO not like", value, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToIn(List<String> values) {
            addCriterion("EMAIL_TO in", values, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToNotIn(List<String> values) {
            addCriterion("EMAIL_TO not in", values, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToBetween(String value1, String value2) {
            addCriterion("EMAIL_TO between", value1, value2, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToNotBetween(String value1, String value2) {
            addCriterion("EMAIL_TO not between", value1, value2, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailTemplateIdIsNull() {
            addCriterion("EMAIL_TEMPLATE_ID is null");
            return (Criteria) this;
        }

        public Criteria andEmailTemplateIdIsNotNull() {
            addCriterion("EMAIL_TEMPLATE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEmailTemplateIdEqualTo(String value) {
            addCriterion("EMAIL_TEMPLATE_ID =", value, "emailTemplateId");
            return (Criteria) this;
        }

        public Criteria andEmailTemplateIdNotEqualTo(String value) {
            addCriterion("EMAIL_TEMPLATE_ID <>", value, "emailTemplateId");
            return (Criteria) this;
        }

        public Criteria andEmailTemplateIdGreaterThan(String value) {
            addCriterion("EMAIL_TEMPLATE_ID >", value, "emailTemplateId");
            return (Criteria) this;
        }

        public Criteria andEmailTemplateIdGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL_TEMPLATE_ID >=", value, "emailTemplateId");
            return (Criteria) this;
        }

        public Criteria andEmailTemplateIdLessThan(String value) {
            addCriterion("EMAIL_TEMPLATE_ID <", value, "emailTemplateId");
            return (Criteria) this;
        }

        public Criteria andEmailTemplateIdLessThanOrEqualTo(String value) {
            addCriterion("EMAIL_TEMPLATE_ID <=", value, "emailTemplateId");
            return (Criteria) this;
        }

        public Criteria andEmailTemplateIdLike(String value) {
            addCriterion("EMAIL_TEMPLATE_ID like", value, "emailTemplateId");
            return (Criteria) this;
        }

        public Criteria andEmailTemplateIdNotLike(String value) {
            addCriterion("EMAIL_TEMPLATE_ID not like", value, "emailTemplateId");
            return (Criteria) this;
        }

        public Criteria andEmailTemplateIdIn(List<String> values) {
            addCriterion("EMAIL_TEMPLATE_ID in", values, "emailTemplateId");
            return (Criteria) this;
        }

        public Criteria andEmailTemplateIdNotIn(List<String> values) {
            addCriterion("EMAIL_TEMPLATE_ID not in", values, "emailTemplateId");
            return (Criteria) this;
        }

        public Criteria andEmailTemplateIdBetween(String value1, String value2) {
            addCriterion("EMAIL_TEMPLATE_ID between", value1, value2, "emailTemplateId");
            return (Criteria) this;
        }

        public Criteria andEmailTemplateIdNotBetween(String value1, String value2) {
            addCriterion("EMAIL_TEMPLATE_ID not between", value1, value2, "emailTemplateId");
            return (Criteria) this;
        }

        public Criteria andBulkEmailMemberNoIsNull() {
            addCriterion("BULK_EMAIL_MEMBER_NO is null");
            return (Criteria) this;
        }

        public Criteria andBulkEmailMemberNoIsNotNull() {
            addCriterion("BULK_EMAIL_MEMBER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andBulkEmailMemberNoEqualTo(String value) {
            addCriterion("BULK_EMAIL_MEMBER_NO =", value, "bulkEmailMemberNo");
            return (Criteria) this;
        }

        public Criteria andBulkEmailMemberNoNotEqualTo(String value) {
            addCriterion("BULK_EMAIL_MEMBER_NO <>", value, "bulkEmailMemberNo");
            return (Criteria) this;
        }

        public Criteria andBulkEmailMemberNoGreaterThan(String value) {
            addCriterion("BULK_EMAIL_MEMBER_NO >", value, "bulkEmailMemberNo");
            return (Criteria) this;
        }

        public Criteria andBulkEmailMemberNoGreaterThanOrEqualTo(String value) {
            addCriterion("BULK_EMAIL_MEMBER_NO >=", value, "bulkEmailMemberNo");
            return (Criteria) this;
        }

        public Criteria andBulkEmailMemberNoLessThan(String value) {
            addCriterion("BULK_EMAIL_MEMBER_NO <", value, "bulkEmailMemberNo");
            return (Criteria) this;
        }

        public Criteria andBulkEmailMemberNoLessThanOrEqualTo(String value) {
            addCriterion("BULK_EMAIL_MEMBER_NO <=", value, "bulkEmailMemberNo");
            return (Criteria) this;
        }

        public Criteria andBulkEmailMemberNoLike(String value) {
            addCriterion("BULK_EMAIL_MEMBER_NO like", value, "bulkEmailMemberNo");
            return (Criteria) this;
        }

        public Criteria andBulkEmailMemberNoNotLike(String value) {
            addCriterion("BULK_EMAIL_MEMBER_NO not like", value, "bulkEmailMemberNo");
            return (Criteria) this;
        }

        public Criteria andBulkEmailMemberNoIn(List<String> values) {
            addCriterion("BULK_EMAIL_MEMBER_NO in", values, "bulkEmailMemberNo");
            return (Criteria) this;
        }

        public Criteria andBulkEmailMemberNoNotIn(List<String> values) {
            addCriterion("BULK_EMAIL_MEMBER_NO not in", values, "bulkEmailMemberNo");
            return (Criteria) this;
        }

        public Criteria andBulkEmailMemberNoBetween(String value1, String value2) {
            addCriterion("BULK_EMAIL_MEMBER_NO between", value1, value2, "bulkEmailMemberNo");
            return (Criteria) this;
        }

        public Criteria andBulkEmailMemberNoNotBetween(String value1, String value2) {
            addCriterion("BULK_EMAIL_MEMBER_NO not between", value1, value2, "bulkEmailMemberNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ALERT_QUEUE
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ALERT_QUEUE
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}