package com.ycs.ezlink.mybatis.dto;

import java.util.Date;

public class OtpUserDtl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EZLINK.OTP_USER_DTL.LOGIN_USER_ID
     *
     * @mbggenerated
     */
    private String loginUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EZLINK.OTP_USER_DTL.OTP_PASSWD
     *
     * @mbggenerated
     */
    private String otpPasswd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EZLINK.OTP_USER_DTL.OTP_SENT_COUNT
     *
     * @mbggenerated
     */
    private Byte otpSentCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EZLINK.OTP_USER_DTL.OTP_VALID_TILL
     *
     * @mbggenerated
     */
    private Date otpValidTill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EZLINK.OTP_USER_DTL.OTP_FN_BLOCKED_TILL
     *
     * @mbggenerated
     */
    private Date otpFnBlockedTill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EZLINK.OTP_USER_DTL.INCORRECT_OTP_CNT
     *
     * @mbggenerated
     */
    private Byte incorrectOtpCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EZLINK.OTP_USER_DTL.CREATED
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EZLINK.OTP_USER_DTL.LOGIN_USER_ID
     *
     * @return the value of EZLINK.OTP_USER_DTL.LOGIN_USER_ID
     *
     * @mbggenerated
     */
    public String getLoginUserId() {
        return loginUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EZLINK.OTP_USER_DTL.LOGIN_USER_ID
     *
     * @param loginUserId the value for EZLINK.OTP_USER_DTL.LOGIN_USER_ID
     *
     * @mbggenerated
     */
    public void setLoginUserId(String loginUserId) {
        this.loginUserId = loginUserId == null ? null : loginUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EZLINK.OTP_USER_DTL.OTP_PASSWD
     *
     * @return the value of EZLINK.OTP_USER_DTL.OTP_PASSWD
     *
     * @mbggenerated
     */
    public String getOtpPasswd() {
        return otpPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EZLINK.OTP_USER_DTL.OTP_PASSWD
     *
     * @param otpPasswd the value for EZLINK.OTP_USER_DTL.OTP_PASSWD
     *
     * @mbggenerated
     */
    public void setOtpPasswd(String otpPasswd) {
        this.otpPasswd = otpPasswd == null ? null : otpPasswd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EZLINK.OTP_USER_DTL.OTP_SENT_COUNT
     *
     * @return the value of EZLINK.OTP_USER_DTL.OTP_SENT_COUNT
     *
     * @mbggenerated
     */
    public Byte getOtpSentCount() {
        return otpSentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EZLINK.OTP_USER_DTL.OTP_SENT_COUNT
     *
     * @param otpSentCount the value for EZLINK.OTP_USER_DTL.OTP_SENT_COUNT
     *
     * @mbggenerated
     */
    public void setOtpSentCount(Byte otpSentCount) {
        this.otpSentCount = otpSentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EZLINK.OTP_USER_DTL.OTP_VALID_TILL
     *
     * @return the value of EZLINK.OTP_USER_DTL.OTP_VALID_TILL
     *
     * @mbggenerated
     */
    public Date getOtpValidTill() {
        return otpValidTill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EZLINK.OTP_USER_DTL.OTP_VALID_TILL
     *
     * @param otpValidTill the value for EZLINK.OTP_USER_DTL.OTP_VALID_TILL
     *
     * @mbggenerated
     */
    public void setOtpValidTill(Date otpValidTill) {
        this.otpValidTill = otpValidTill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EZLINK.OTP_USER_DTL.OTP_FN_BLOCKED_TILL
     *
     * @return the value of EZLINK.OTP_USER_DTL.OTP_FN_BLOCKED_TILL
     *
     * @mbggenerated
     */
    public Date getOtpFnBlockedTill() {
        return otpFnBlockedTill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EZLINK.OTP_USER_DTL.OTP_FN_BLOCKED_TILL
     *
     * @param otpFnBlockedTill the value for EZLINK.OTP_USER_DTL.OTP_FN_BLOCKED_TILL
     *
     * @mbggenerated
     */
    public void setOtpFnBlockedTill(Date otpFnBlockedTill) {
        this.otpFnBlockedTill = otpFnBlockedTill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EZLINK.OTP_USER_DTL.INCORRECT_OTP_CNT
     *
     * @return the value of EZLINK.OTP_USER_DTL.INCORRECT_OTP_CNT
     *
     * @mbggenerated
     */
    public Byte getIncorrectOtpCnt() {
        return incorrectOtpCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EZLINK.OTP_USER_DTL.INCORRECT_OTP_CNT
     *
     * @param incorrectOtpCnt the value for EZLINK.OTP_USER_DTL.INCORRECT_OTP_CNT
     *
     * @mbggenerated
     */
    public void setIncorrectOtpCnt(Byte incorrectOtpCnt) {
        this.incorrectOtpCnt = incorrectOtpCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EZLINK.OTP_USER_DTL.CREATED
     *
     * @return the value of EZLINK.OTP_USER_DTL.CREATED
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EZLINK.OTP_USER_DTL.CREATED
     *
     * @param created the value for EZLINK.OTP_USER_DTL.CREATED
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}