package com.ycs.ezlink.mybatis.mapper;

import com.ycs.ezlink.mybatis.dto.AlertQueue;
import com.ycs.ezlink.mybatis.dto.AlertQueueExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface AlertQueueMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ALERT_QUEUE
	 * @mbggenerated
	 */
	int countByExample(AlertQueueExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ALERT_QUEUE
	 * @mbggenerated
	 */
	int deleteByExample(AlertQueueExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ALERT_QUEUE
	 * @mbggenerated
	 */
	@Delete({ "delete from ALERT_QUEUE", "where ALERT_Q_ID = #{alertQId,jdbcType=DECIMAL}" })
	int deleteByPrimaryKey(Integer alertQId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ALERT_QUEUE
	 * @mbggenerated
	 */
	@Insert({ "insert into ALERT_QUEUE (ALERT_Q_ID, ALERT_TYPE, ", "USER_ID, SMS_TEXT, ", "EMAIL_TEXT, CREATE_TIME, ", "SCHEDULED_TIME, DELIVERED_STATUS, ", "RETRY_COUNT, MOBILE_NO, ",
			"EMAIL_TO, EMAIL_TEMPLATE_ID, ", "BULK_EMAIL_MEMBER_NO)", "values (#{alertQId,jdbcType=DECIMAL}, #{alertType,jdbcType=VARCHAR}, ",
			"#{userId,jdbcType=VARCHAR}, #{smsText,jdbcType=VARCHAR}, ", "#{emailText,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
			"#{scheduledTime,jdbcType=TIMESTAMP}, #{deliveredStatus,jdbcType=VARCHAR}, ", "#{retryCount,jdbcType=DECIMAL}, #{mobileNo,jdbcType=VARCHAR}, ",
			"#{emailTo,jdbcType=VARCHAR}, #{emailTemplateId,jdbcType=VARCHAR}, ", "#{bulkEmailMemberNo,jdbcType=VARCHAR})" })
	int insert(AlertQueue record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ALERT_QUEUE
	 * @mbggenerated
	 */
	int insertSelective(AlertQueue record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ALERT_QUEUE
	 * @mbggenerated
	 */
	List<AlertQueue> selectByExample(AlertQueueExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ALERT_QUEUE
	 * @mbggenerated
	 */
	@Select({ "select", "ALERT_Q_ID, ALERT_TYPE, USER_ID, SMS_TEXT, EMAIL_TEXT, CREATE_TIME, SCHEDULED_TIME, ",
			"DELIVERED_STATUS, RETRY_COUNT, MOBILE_NO, EMAIL_TO, EMAIL_TEMPLATE_ID, BULK_EMAIL_MEMBER_NO", "from ALERT_QUEUE", "where ALERT_Q_ID = #{alertQId,jdbcType=DECIMAL}" })
	@ResultMap("BaseResultMap")
	AlertQueue selectByPrimaryKey(Integer alertQId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ALERT_QUEUE
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") AlertQueue record, @Param("example") AlertQueueExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ALERT_QUEUE
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") AlertQueue record, @Param("example") AlertQueueExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ALERT_QUEUE
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(AlertQueue record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ALERT_QUEUE
	 * @mbggenerated
	 */
	@Update({ "update ALERT_QUEUE", "set ALERT_TYPE = #{alertType,jdbcType=VARCHAR},", "USER_ID = #{userId,jdbcType=VARCHAR},", "SMS_TEXT = #{smsText,jdbcType=VARCHAR},",
			"EMAIL_TEXT = #{emailText,jdbcType=VARCHAR},", "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},", "SCHEDULED_TIME = #{scheduledTime,jdbcType=TIMESTAMP},",
			"DELIVERED_STATUS = #{deliveredStatus,jdbcType=VARCHAR},", "RETRY_COUNT = #{retryCount,jdbcType=DECIMAL},", "MOBILE_NO = #{mobileNo,jdbcType=VARCHAR},",
			"EMAIL_TO = #{emailTo,jdbcType=VARCHAR},", "EMAIL_TEMPLATE_ID = #{emailTemplateId,jdbcType=VARCHAR},", "BULK_EMAIL_MEMBER_NO = #{bulkEmailMemberNo,jdbcType=VARCHAR}",
			"where ALERT_Q_ID = #{alertQId,jdbcType=DECIMAL}" })
	int updateByPrimaryKey(AlertQueue record);
}