package com.ycs.ezlink.mybatis.mapper;

import com.ycs.ezlink.mybatis.dto.AlertTemplateMaster;
import com.ycs.ezlink.mybatis.dto.AlertTemplateMasterExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface AlertTemplateMasterMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ALERT_TEMPLATE_MASTER
	 * @mbggenerated
	 */
	int countByExample(AlertTemplateMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ALERT_TEMPLATE_MASTER
	 * @mbggenerated
	 */
	int deleteByExample(AlertTemplateMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ALERT_TEMPLATE_MASTER
	 * @mbggenerated
	 */
	@Delete({ "delete from ALERT_TEMPLATE_MASTER", "where ALERT_TEMPLATE_ID = #{alertTemplateId,jdbcType=VARCHAR}" })
	int deleteByPrimaryKey(String alertTemplateId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ALERT_TEMPLATE_MASTER
	 * @mbggenerated
	 */
	@Insert({ "insert into ALERT_TEMPLATE_MASTER (ALERT_TEMPLATE_ID, ALERT_TYPE, ", "ALERT_CONTENT, SMS_PASSWORD, ", "SMS_USERID, TECH_STUDIO_CAMPAIGN_ID, ", "EMAIL_SUBJECT)",
			"values (#{alertTemplateId,jdbcType=VARCHAR}, #{alertType,jdbcType=VARCHAR}, ", "#{alertContent,jdbcType=VARCHAR}, #{smsPassword,jdbcType=VARCHAR}, ",
			"#{smsUserid,jdbcType=VARCHAR}, #{techStudioCampaignId,jdbcType=VARCHAR}, ", "#{emailSubject,jdbcType=VARCHAR})" })
	int insert(AlertTemplateMaster record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ALERT_TEMPLATE_MASTER
	 * @mbggenerated
	 */
	int insertSelective(AlertTemplateMaster record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ALERT_TEMPLATE_MASTER
	 * @mbggenerated
	 */
	List<AlertTemplateMaster> selectByExample(AlertTemplateMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ALERT_TEMPLATE_MASTER
	 * @mbggenerated
	 */
	@Select({ "select", "ALERT_TEMPLATE_ID, ALERT_TYPE, ALERT_CONTENT, SMS_PASSWORD, SMS_USERID, TECH_STUDIO_CAMPAIGN_ID, ", "EMAIL_SUBJECT", "from ALERT_TEMPLATE_MASTER",
			"where ALERT_TEMPLATE_ID = #{alertTemplateId,jdbcType=VARCHAR}" })
	@ResultMap("BaseResultMap")
	AlertTemplateMaster selectByPrimaryKey(String alertTemplateId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ALERT_TEMPLATE_MASTER
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") AlertTemplateMaster record, @Param("example") AlertTemplateMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ALERT_TEMPLATE_MASTER
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") AlertTemplateMaster record, @Param("example") AlertTemplateMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ALERT_TEMPLATE_MASTER
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(AlertTemplateMaster record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ALERT_TEMPLATE_MASTER
	 * @mbggenerated
	 */
	@Update({ "update ALERT_TEMPLATE_MASTER", "set ALERT_TYPE = #{alertType,jdbcType=VARCHAR},", "ALERT_CONTENT = #{alertContent,jdbcType=VARCHAR},",
			"SMS_PASSWORD = #{smsPassword,jdbcType=VARCHAR},", "SMS_USERID = #{smsUserid,jdbcType=VARCHAR},", "TECH_STUDIO_CAMPAIGN_ID = #{techStudioCampaignId,jdbcType=VARCHAR},",
			"EMAIL_SUBJECT = #{emailSubject,jdbcType=VARCHAR}", "where ALERT_TEMPLATE_ID = #{alertTemplateId,jdbcType=VARCHAR}" })
	int updateByPrimaryKey(AlertTemplateMaster record);
}